# super-linter: skip=yaml
# super-linter: skip=actionlint
# super-linter: skip=shell
---
name: Lint
on:
  push:
    paths:
      - 'lamm/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        env:
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}
        run: git diff --name-only $BASE...$HEAD
      - name: Run linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: test
          FILTER_REGEX_INCLUDE: .*lamm/.*
        with:
          lint-staged: ${{ steps.changed-files.outputs.files }}
      - name: Set Success Status
        run: |
          exit 0
