# super-linter: skip=yaml
# super-linter: skip=actionlint
# super-linter: skip=shell
---
name: Lint
on:
  push:
    paths:
      - 'lamm/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        id: get_changed_files
        uses: jitterbit/get-changed-files@v1
      - name: Run linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: test
          FILTER_REGEX_INCLUDE: '${{ steps.get_changed_files.outputs.all }}'
